# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gen_files/lobby_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gen_files/lobby_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgen_files/lobby_service.proto\"\x14\n\x12ListLobbiesRequest\".\n\x13ListLobbiesResponse\x12\x17\n\x07lobbies\x18\x01 \x03(\x0b\x32\x06.Lobby\"\x13\n\x05Lobby\x12\n\n\x02id\x18\x01 \x01(\t2H\n\x0cLobbyService\x12\x38\n\x0bListLobbies\x12\x13.ListLobbiesRequest\x1a\x14.ListLobbiesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gen_files.lobby_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTLOBBIESREQUEST']._serialized_start=33
  _globals['_LISTLOBBIESREQUEST']._serialized_end=53
  _globals['_LISTLOBBIESRESPONSE']._serialized_start=55
  _globals['_LISTLOBBIESRESPONSE']._serialized_end=101
  _globals['_LOBBY']._serialized_start=103
  _globals['_LOBBY']._serialized_end=122
  _globals['_LOBBYSERVICE']._serialized_start=124
  _globals['_LOBBYSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
