# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import lobby_service_pb2 as proto_dot_lobby__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/lobby_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LobbyServiceStub(object):
    """Service for managing game lobbies. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListLobbies = channel.unary_unary(
                '/LobbyService/ListLobbies',
                request_serializer=proto_dot_lobby__service__pb2.ListLobbiesRequest.SerializeToString,
                response_deserializer=proto_dot_lobby__service__pb2.ListLobbiesResponse.FromString,
                _registered_method=True)


class LobbyServiceServicer(object):
    """Service for managing game lobbies. 
    """

    def ListLobbies(self, request, context):
        """Get a list of all lobbies. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LobbyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListLobbies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLobbies,
                    request_deserializer=proto_dot_lobby__service__pb2.ListLobbiesRequest.FromString,
                    response_serializer=proto_dot_lobby__service__pb2.ListLobbiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LobbyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LobbyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LobbyService(object):
    """Service for managing game lobbies. 
    """

    @staticmethod
    def ListLobbies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LobbyService/ListLobbies',
            proto_dot_lobby__service__pb2.ListLobbiesRequest.SerializeToString,
            proto_dot_lobby__service__pb2.ListLobbiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
